# Generated by Django 5.1.1 on 2024-09-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=200)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stridewell.workout')),
            ],
        ),
    ]
