# Generated by Django 5.1.1 on 2024-09-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stridewell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutstep',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
