# Generated by Django 5.1.1 on 2024-09-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stridewell', '0002_rename_workout_id_workoutstep_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workoutstep',
            old_name='step_name',
            new_name='name',
        ),
    ]
